export const server_obj = [
    {
        id: 1,
        lable: "Full Name",
        type: "text",
        name: "name",
        placeholder: "Full Name",
        minLength: 3,
        maxLength: 20,
        required: true,
    },
    {
        id: 2,
        lable: "Date of Birth",
        type: "date",
        name: "DOB",
        // placeholder: "Date of Birth",
        // minLength: 3,
        // maxLength: 20,
        required: true,
    },
    {
        id: 3,
        lable: "Gender",
        type: "radio",
        name: "gender",
        options: ["Male", "Female", "Other"],
        // placeholder: "Enter Full Name",
        // minLength: 3,
        // maxLength: 20,
        required: true,
    },
    {
        id: 4,
        lable: "Student Number",
        type: "number",
        name: "studentNumber",
        placeholder: "Student Number",
        minLength: 10,
        maxLength: 10,
        required: true,
    },
    {
        id: 5,
        lable: "Parent Number",
        type: "number",
        name: "parentNumber",
        placeholder: "Parent Number",
        minLength: 10,
        maxLength: 10,
        required: true,
    },
    {
        id: 6,
        lable: "Email ID",
        type: "email",
        name: "emailID",
        placeholder: "Email ID",
        minLength: 11,
        maxLength: 30,
        required: true,
    },
    {
        id: 7,
        lable: "City / Village Name",
        type: "text",
        name: "city",
        placeholder: "City or Village Name",
        minLength: 3,
        maxLength: 20,
        required: true,
    },
    {
        id: 8,
        lable: "School / College Name",
        type: "text",
        name: "collegeName",
        placeholder: "School or College Name",
        minLength: 3,
        maxLength: 50,
        required: true,
    },
    {
        id: 9,
        lable: "Department",
        type: "text",
        name: "department",
        placeholder: "Department",
        // minLength: 3,
        maxLength: 30,
        required: true,
    },
    {
        id: 10,
        lable: "Course",
        type: "dropdown",
        name: "Course",
        options: ["Full Stack", "Data Science", "Machine Learning", "Digital Marketing"],
        placeholder: "Course",
        // minLength: 3,
        // maxLength: 20,
        required: true,
    },
    {
        id: 11,
        lable: "Course Fees",
        type: "number",
        name: "courseFees",
        placeholder: "Course Fees",
        minLength: 1,
        maxLength: 20,
        required: true,
    },
    {
        id: 12,
        lable: "Discount (if any)",
        type: "number",
        name: "Discount",
        placeholder: "Discount",
        maxLength: 5,
        required: false,
    },
    {
        id: 13,
        lable: "Student Batch ID",
        type: "text",
        name: "studentBatchId",
        placeholder: "Student Batch ID",
        required: true,
    },
    {
        id: 14,
        lable: "Assigned Mentor Name",
        type: "dropdown",
        name: "mentorName",
        options: ["Kalai", "Arsath", "Riswan", "Thanam", "Monika", "Hema", "Vicky"],
        placeholder: "Assigned Mentor Name",
        // minLength: 3,
        // maxLength: 50,
        required: true,
    },
    {
        id: 15,
        lable: "Coaching Timing",
        type: "time",
        time: ["Start Time", "End Time"],
        name: ["startTime","endTime"],
        // placeholder: "School or College Name",
        // minLength: 3,
        // maxLength: 50,
        required: true,
    },
    {
        id: 16,
        lable: "Batch Starting Date",
        type: "date",
        name: "batchStartingDate",
        // placeholder: "School or College Name",
        // minLength: 3,
        // maxLength: 50,
        required: true,
    },
    {
        id: 17,
        lable: "Student Photo",
        type: "double_button",
        name: "photo",
        // placeholder: "Enter Full Name",
        // minLength: 3,
        // maxLength: 20,
        required: true,
    },

]

export const inp_def_vals = {
    name: "",
    DOB: "",
    gender: "Male",
    photo: "",
    studentNumber: "",
    parentNumber: "",
    emailID: "",
    city: "",
    collegeName: "",
    department: "",
    Course: "",
    courseFees: "",
    Discount: "",
    studentBatchId: "",
    mentorName: "",
    startTime: "",
    endTime: "",
    batchStartingDate: "",
}
